version: 2.1

jobs:
  build-and-test:
    docker:
      - image: python:3.6.0
    steps:
      - checkout
      - run:
          name: Install and Test
          command: |
            pip3 install -r requirements.txt
            pip3 install --upgrade -e .
            xvfb python3 -m unittest discover

workflows:
  main:
    jobs:
      - build-and-test
